services:
  mysql:
    image: matthewtranmer/gws-mysql
    volumes:
      - sensor-storage:/var/lib/mysql
      - ./secrets/:/secrets:ro
    networks:
      - sensor-net
    
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ONETIME_PASSWORD=yes
      - MYSQL_USER=WorkerRW
      - MYSQL_PASSWORD_FILE=/secrets/dbpassword
      - MYSQL_DATABASE=sensor

  webapp:
    image: matthewtranmer/gws-webapp
    networks:
      - sensor-net
    volumes:
      - ./secrets/:/secrets:ro
    environment:
      - DATABASE_SECRET_FILE=/secrets/dbpassword
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: matthewtranmer/gws-nginx
    networks:
      - sensor-net
    ports:
      - 80:80
    depends_on:
      webapp:
        condition: service_healthy

  sensor:
    image: matthewtranmer/gws-sensor
    networks:
      - sensor-net
    volumes:
      - ./secrets/:/secrets:ro
    devices:
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - DATABASE_SECRET_FILE=/secrets/dbpassword
      - TRIGGER=14
      - ECHO=15
    depends_on:
      mysql:
        condition: service_healthy

networks:
  sensor-net:
    driver: bridge

volumes:
  sensor-storage:
    external: true
